-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Waktu pembuatan: 18 Jan 2024 pada 18.34
-- Versi server: 10.4.28-MariaDB
-- Versi PHP: 8.0.28

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `db_sentimen`
--

-- --------------------------------------------------------

--
-- Struktur dari tabel `tweets`
--

CREATE TABLE `tweets` (
  `id` int(12) NOT NULL,
  `id_tweet` varchar(100) NOT NULL,
  `text_dirty` text NOT NULL,
  `text_clean` text NOT NULL,
  `text_steam` text NOT NULL,
  `label` varchar(30) NOT NULL,
  `hand_label` varchar(30) NOT NULL,
  `tgl_ambil` datetime NOT NULL,
  `hastag` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data untuk tabel `tweets`
--

INSERT INTO `tweets` (`id`, `id_tweet`, `text_dirty`, `text_clean`, `text_steam`, `label`, `hand_label`, `tgl_ambil`, `hastag`) VALUES
(1, '1733999734971630000', 'SYL sengaja mengungkap adanya dua oknum di parpol berbeda terlibat dalam kasus hukum yang menjeratnya, karena punya motif politik.  Apalagi, Efriza mendapati pernyataan kuasa hukum SYL menyebutkan, keterlibatan dua elite parpol ada kaitannya dengan penundaan pemilu, apabila namaâ€¦ https://t.co/kEfrC2rIaa', 'SYL sengaja mengungkap adanya dua oknum di parpol berbeda terlibat dalam kasus hukum yang menjeratnya, karena punya motif politik.  Apalagi, Efriza mendapati pernyataan kuasa hukum SYL menyebutkan, keterlibatan dua elite parpol ada kaitannya dengan penundaan pemilu, apabila namaâ', 'syl sengaja mengungkap adanya dua oknum di parpol berbeda terlibat dalam kasus hukum yang menjeratnya karena punya motif politik apalagi efriza mendapati pernyataan kuasa hukum syl menyebutkan keterlibatan dua elite parpol ada kaitannya dengan penundaan pemilu apabila nama', 'netral', '', '2023-12-10 23:58:47', 'pemilu2024'),
(2, '1733999700196660000', '#TemanPemilih KPU Kabupaten Banjarnegara melaksanakan Rapat Kerja Pemanfaatan Teknologi Informasi Dalam Penentuan Titik Koordinat TPS dan Persiapan Pemutakhiran DPTb bulan November Untuk Pemilu Tahun 2024. Sabtu, 2/12 di Kopi Krajan, Semampir, Banjarnegara.  #KPUMelayani https://t.co/Jv1AZYrMKu', 'KPU Kabupaten Banjarnegara melaksanakan Rapat Kerja Pemanfaatan Teknologi Informasi Dalam Penentuan Titik Koordinat TPS dan Persiapan Pemutakhiran DPTb bulan November Untuk Pemilu Tahun 2024. Sabtu, 2/12 di Kopi Krajan, Semampir, Banjarnegara.', 'kpu kabupaten banjarnegara melaksanakan rapat Kerja pemanfaatan teknologi informasi dalam penentuan titik koordinat tps dan persiapan pemutakhiran dptb bulan november untuk pemilu tahun 2024 sabtu 2 12 di kopi krajan semampir banjarnegara', 'netral', '', '2023-12-10 23:58:39', 'pemilu2024'),
(3, '1733999663832060000', '@cobeh2022 Ketika ambisi mengalahkan nilai nilai demokrasi. Ketidak tegasan presiden dan bawaslu terhadap mentri yang ikut kontestan pemilu akhirnya melabrak demokrasi itu sendiri  Presiden dan bawaslu ikut dalam mendukung pemilu yang tidak fair.', 'Ketika ambisi mengalahkan nilai nilai demokrasi. Ketidak tegasan presiden dan bawaslu terhadap mentri yang ikut kontestan pemilu akhirnya melabrak demokrasi itu sendiri  Presiden dan bawaslu ikut dalam mendukung pemilu yang tidak fair.', 'ketika ambisi mengalahkan nilai nilai demokrasi ketidak tegasan presiden dan bawaslu terhadap mentri yang ikut kontestan pemilu akhirnya melabrak demokrasi itu sendiri  presiden dan bawaslu ikut dalam mendukung pemilu yang tidak fair', 'negatif', '', '2023-12-10 23:58:30', 'pemilu2024'),
(4, '1733999539710010000', '#TemanPemilih, Pendaftaran KPPS Pemilu 2024 sudah dibuka. Ayoo daftarkan diri anda...  Informasi selengkapnya dapat dilihat melalui link https://t.co/5llEceDiWp atau melalui scan barcode.  #ppsbukowedung #kpudemak https://t.co/X69nfaJfSy', ',Pendaftaran KPPS Pemilu 2024 sudah dibuka.Ayoo daftarkan diri anda...  Informasi selengkapnya dapat dilihat melalui link atau melalui scan barcode.  ', 'pendaftaran kpps pemilu 2024 sudah dibuka ayoo daftarkan diri anda informasi selengkapnya dapat dilihat melalui link atau melalui scan barcode', 'netral', '', '2023-12-10 23:58:01', 'pemilu2024'),
(5, '1733998899059380000', 'Assalamu\'alaikum Saudaraku ... Mohon Do\'a &amp  dukungan serta pilihannya Dengan mencoblos Nomor urut 5 Dapil 1 M HENDRI M NUR SH kertas warna hijau Untuk DPRD II KABUPATEN BUNGO Dari Partai Golkar NO. 4 Pada Pemilu RABU 14 Pebruari 2024 nanti https://t.co/sJKlaE3kCY', 'Assalamu\'alaikum Saudaraku ... Mohon Do\'a &amp  dukungan serta pilihannya Dengan mencoblos Nomor urut 5 Dapil 1 M HENDRI M NUR SH kertas warna hijau Untuk DPRD II KABUPATEN BUNGO Dari Partai Golkar NO. 4 Pada Pemilu RABU 14 Pebruari 2024 nanti ', 'assalamualaikum saudaraku mohon doa amp  dukungan serta pilihannya dengan mencoblos nomor urut 5 dapil 1 m hendri m nur sh kertas warna hijau untuk dprd II kabupaten bungo dari partai golkar no 4 pada pemilu rabu 14 pebruari 2024 nanti ', 'positif', '', '2023-12-10 23:55:28', 'pemilu2024'),
(6, '1733998822324580000', 'Keunikan Faktor Selera dalam Menentukan Permintaan Konsumen atau Pemilih dalam Pemilu https://t.co/w5DBnFnB7K', 'Keunikan Faktor Selera dalam Menentukan Permintaan Konsumen atau Pemilih dalam Pemilu', 'keunikan faktor selera dalam menentukan permintaan konsumen atau pemilih dalam pemilu ', 'netral', '', '2023-12-10 23:55:10', 'pemilu2024'),
(7, '1733998442526150000', '#temanpemilih KPU Kabupaten Banjarnegara melaksanakan Media Gathering Dan Sosialisasi Kampanye Pemilu Tahun 2024 bersama PWI Kabupaten Banjarnegara, Jum\'at 1/12.  #KPUMelayani  #PemiluSerentak2024 https://t.co/wFmEBFAaW9', 'KPU Kabupaten Banjarnegara melaksanakan Media Gathering Dan Sosialisasi Kampanye Pemilu Tahun 2024 bersama PWI Kabupaten Banjarnegara, Jum\'at 1/12.', 'kpu kabupaten banjarnegara melaksanakan media gathering dan sosialisasi kampanye pemilu tahun 2024 bersama pwi kabupaten banjarnegara jumat 1 12', 'positif', '', '2023-12-10 23:53:39', 'pemilu2024'),
(8, '1733998428198500000', 'Capek banget lihat keadaan dunia sekarang ini, banyak sekali keributan 1. Perang yang tak kunjung usai 2.Kedatangan warga asing di Indonesia secara ilegal tapi dibekingin sama lembaga dunia yang katanya kemanusiaan.  3. Keributan antar agama gara gara sebuah podcast 4. Pemilu 5.', 'Capek banget lihat keadaan dunia sekarang ini, banyak sekali keributan 1. Perang yang tak kunjung usai 2.Kedatangan warga asing di Indonesia secara ilegal tapi dibekingin sama lembaga dunia yang katanya kemanusiaan.  3. Keributan antar agama gara gara sebuah podcast 4. Pemilu 5.', 'capek banget lihat keadaan dunia sekarang ini banyak sekali keributan 1 perang yang tak kunjung usai 2 kedatangan warga asing di indonesia secara ilegal tapi dibekingin sama lembaga dunia yang katanya kemanusiaan  3 Keributan antar agama gara gara sebuah podcast 4 Pemilu 5', 'negatif', '', '2023-12-10 23:53:36', 'pemilu2024'),
(9, '1733998108449870000', '@Dennysiregar7 Film pemilu 2024 Bang', 'Film pemilu 2024 Bang', 'film pemilu 2024 bang', 'positif', '', '2023-12-10 23:52:19', 'pemilu2024'),
(10, '1733997609248010000', '@Widya_Makmur11 @bawaslu_RI Bener krn fakta di lapangan tlh membuktikan bahkan ada video yg tersebar apa masih kurang bukti ? Jika Panwaslu memiliki nyali dan komitmen untuk menyelenggarakan pemilu secara jujur dan adil tentu atas amanat UU semua itu akan ditindak tanpa melihat dr paslon mana yg melanggar.', 'Bener krn fakta di lapangan tlh membuktikan bahkan ada video yg tersebar apa masih kurang bukti ? Jika Panwaslu memiliki nyali dan komitmen untuk menyelenggarakan pemilu secara jujur dan adil tentu atas amanat UU semua itu akan ditindak tanpa melihat dr paslon mana yg melanggar.', 'bener krn fakta di lapangan tlh membuktikan bahkan ada video yg tersebar apa masih kurang bukti jika panwaslu memiliki nyali dan komitmen untuk menyelenggarakan pemilu secara jujur dan adil tentu atas amanat uu semua itu akan ditindak tanpa melihat dr paslon mana yg melanggar.', 'positif', '', '2023-12-10 23:50:20', 'pemilu2024'),
(11, '1733997606278460000', 'fyp tiktok isinya polemik dan propaganda islam-kristen sama pemilu pilpres. sometimes responding but not too hard. so much more skipping them. pokoknya gw udah tau tgl 14 mau pilih yg mana.', 'fyp tiktok isinya polemik dan propaganda islam-kristen sama pemilu pilpres. sometimes responding but not too hard. so much more skipping them. pokoknya gw udah tau tgl 14 mau pilih yg mana.', 'fyp tiktok isinya polemik dan propaganda islam kristen sama pemilu pilpres sometimes responding but not too hard so much more skipping them pokoknya gw udah tau tgl 14 mau pilih yg mana', 'negatif', '', '2023-12-10 23:50:20', 'pemilu2024'),
(12, '1733997266330160000', 'KPU telah mempersiapkan sarana dan prasarana bagi semua pemilih pada Pemilu tahun 2024 termasuk bagi Disabilitas. layanan bagi Disabilitas diberikan di semua TPS seperti adanya Templet bagi Pemilih Tuna Netra  ___ Chelsea Roma Messi Girona #viralvideo Menhan Caicedo https://t.co/c9BsbFUEz3', 'KPU telah mempersiapkan sarana dan prasarana bagi semua pemilih pada Pemilu tahun 2024 termasuk bagi Disabilitas. layanan bagi Disabilitas diberikan di semua TPS seperti adanya Templet bagi Pemilih Tuna Netra', 'kpu telah mempersiapkan sarana dan prasarana bagi semua pemilih pada pemilu tahun 2024 termasuk bagi disabilitas layanan bagi disabilitas diberikan di semua tps seperti adanya templet bagi pemilih tuna netra ', 'positif', '', '2023-12-10 23:48:59', 'pemilu2024'),
(13, '1733997187783320000', 'Udah mengacak-acak UU KPK Udah merubah UU Pemilu Sudah Merubah RUU DKJ Presiden tunjuk GUB DKI  Ngomong sok paling taat UU....ASEM lho!!!!!', 'Udah mengacak-acak UU KPK Udah merubah UU Pemilu Sudah Merubah RUU DKJ Presiden tunjuk GUB DKI  Ngomong sok paling taat UU....ASEM lho!!!!!', 'udah mengacak-acak uu kpk udah merubah uu pemilu sudah merubah ruu dkj presiden tunjuk gub dki  ngomong sok paling taat uu asem lho', 'negatif', '', '2023-12-10 23:48:40', 'pemilu2024'),
(14, '1733997061048310000', '@Yusrilihza_Mhd Kekuasaan &amp  bagi2 jabatan yg diharapkan nanti dgn terplhnya PS&amp G Orang2 cerdik cendiawan Pemilu kali ini bener2 sdh tdk BS dipercaya lagi', 'Kekuasaan &amp  bagi2 jabatan yg diharapkan nanti dgn terplhnya PS&amp G Orang2 cerdik cendiawan Pemilu kali ini bener2 sdh tdk BS dipercaya lagi', 'kekuasaan amp bagi2 jabatan yg diharapkan nanti dgn terplhnya psamp g Orang2 cerdik cendiawan pemilu kali ini bener2 sdh tdk bs dipercaya lagi', 'negatif', '', '2023-12-10 23:48:10', 'pemilu2024'),
(15, '1733996959013420000', '@Andria75777 Enaknye jadi ketua KPU /BAWASLU Pemilu 2024,monggo yg Upetinye gede yg minta di menangkan jd PRESIDEN 2024...1trilyun 2triliun ðŸ‘»ðŸ‘»ðŸ‘»ðŸ’©ðŸ’©ðŸ’©ðŸ·ðŸ·ðŸ·ðŸ¤®ðŸ¤®ðŸ¤®', 'Enaknye jadi ketua KPU /BAWASLU Pemilu 2024,monggo yg Upetinye gede yg minta di menangkan jd PRESIDEN 2024...1trilyun 2triliun ', 'enaknye jadi ketua kpu bawaslu pemilu 2024 monggo yg upetinye gede yg minta di menangkan jd presiden 2024 1trilyun 2triliun ', 'negatif', '', '2023-12-10 23:47:45', 'pemilu2024'),
(16, '1733996858668910000', '@Fahrihamzah Gue dukung paslon 02 pada PEMILU 2024 H', 'Gue dukung paslon 02 pada PEMILU 2024 H', 'gue dukung paslon 02 pada pemilu 2024 h', 'positif', '', '2023-12-10 23:47:21', 'pemilu2024'),
(17, '1733996763626000000', '@Gus_Raharjo Kok pake fasilitas negara buat pemilu,, gak bener banget sih ini', 'Kok pake fasilitas negara buat pemilu,, gak bener banget sih ini', 'kok pake fasilitas negara buat pemilu gak bener banget sih ini', 'negatif', '', '2023-12-10 23:46:59', 'pemilu2024'),
(18, '1733996750908890000', '@liputan6dotcom Sehat selalu ya mahdud. Sukses dan lancar menuju pemilu', 'Sehat selalu ya mahdud. Sukses dan lancar menuju pemilu', 'sehat selalu ya mahdud sukses dan lancar menuju pemilu', 'positif', '', '2023-12-10 23:46:56', 'pemilu2024'),
(19, '1733996749881250000', '@hermantoregar Coba tebak mas, saya kira2 pilih siapa di Pemilu?  Dengan data ini : No 1. Saya bersahabat dg PKB.  No 2. Saya bersahabat dengan PDIP.  3.Saya bersahabat dengan PD.  No 4. Saya bersahabat dg non Parpol.  No 5. Saya bersahabat dengan PD USA.  No 6. Saya bersahabat dg diri sendiri.', 'Coba tebak mas, saya kira2 pilih siapa di Pemilu?  Dengan data ini : No 1. Saya bersahabat dg PKB.  No 2. Saya bersahabat dengan PDIP.  3.Saya bersahabat dengan PD.  No 4. Saya bersahabat dg non Parpol.  No 5. Saya bersahabat dengan PD USA.  No 6. Saya bersahabat dg diri sendiri.', 'coba tebak mascsaya kira2 pilih siapa di Pemilu dengan data ini no 1 saya bersahabat dg pkb no 2 saya bersahabat dengan pdip 3 saya bersahabat dengan pd  no 4 saya bersahabat dg non parpol no 5 saya bersahabat dengan pd usa no 6 saya bersahabat dg diri sendiri', 'netral', '', '2023-12-10 23:46:55', 'pemilu2024'),
(20, '1733996507827920000', 'mending ga usah diadakan pemilu, lngsung dilantik sekalian..', 'mending ga usah diadakan pemilu, lngsung dilantik sekalian..', 'mending ga usah diadakan pemilu lngsung dilantik sekalian', 'netral', '', '2023-12-10 23:45:58', 'pemilu2024'),
(21, '1733996494733340000', 'Hallo #TemanPemilih, pendaftaran Anggota Kelompok Penyelenggara Pemungutan Suara (KPPS) Pemilu 2024 sudah di buka nih.  .  Selengkapnya, cek di postingan yaðŸ¤— .  #KPUMelayani #PemiluSerentak2024 https://t.co/PjXlOTGbXn', 'Hallo , pendaftaran Anggota Kelompok Penyelenggara Pemungutan Suara (KPPS) Pemilu 2024 sudah di buka nih.  .  Selengkapnya, cek di postingan ', 'hallo pendaftaran anggota kelompok penyelenggara pemungutan suara kpps pemilu 2024 sudah di buka nih selengkapnya cek di postingan ', 'positif', '', '2023-12-10 23:45:55', 'pemilu2024'),
(22, '1733996327305170000', 'Gokils satu KK ? Pemilu bisa ambyar', 'Gokils satu KK ? Pemilu bisa ambyar', 'gokils satu kk  pemilu bisa ambyar', 'netral', '', '2023-12-10 23:45:15', 'pemilu2024'),
(23, '1733996096387710000', 'Perempuan Indonesia Jangan Ragu Gunakan Hak Suaranya  Peran perempuan dalam pesta demokrasi merupakan isu strategis sebagai usaha utk menjunjung tinggi hak asasi perempuan dan jangan ragu lagi menggunakan hak suaranya pada pemilu 2024  Chelsea Roma Messi Girona #viralvideo Menhan https://t.co/Txm0J1az47', 'Perempuan Indonesia Jangan Ragu Gunakan Hak Suaranya  Peran perempuan dalam pesta demokrasi merupakan isu strategis sebagai usaha utk menjunjung tinggi hak asasi perempuan dan jangan ragu lagi menggunakan hak suaranya pada pemilu 2024  ', 'perempuan indonesia jangan ragu gunakan hak suaranya  peran perempuan dalam pesta demokrasi merupakan isu strategis sebagai usaha utk menjunjung tinggi hak asasi perempuan dan jangan ragu lagi menggunakan hak suaranya pada pemilu 2024  ', 'positif', '', '2023-12-10 23:44:20', 'pemilu2024'),
(24, '', 'Nganu\' maksud saya jelang pemilu, pemilunya kan masih tahun depan 2 bulan lagi ðŸ˜', 'Nganu\' maksud saya jelang pemilu, pemilunya kan masih tahun depan 2 bulan lagi', 'nganu maksud saya jelang pemilu pemilunya kan masih tahun depan 2 bulan lagi', 'nettral', '', '2023-12-10 23:43:59', 'pemilu2024'),
(25, '1733995767369750000', 'Ngerasa gak Pemilu tahun ini beda, gak seperti 5 tahun lalu.', 'Ngerasa gak Pemilu tahun ini beda, gak seperti 5 tahun lalu.', 'ngerasa gak pemilu tahun ini beda gak seperti 5 tahun lalu', 'netral', '', '2023-12-10 23:43:01', 'pemilu2024'),
(26, '1733995445113010000', '@PribumiD @Gede_86 Lagi sibuk persiapan pemilu', 'Lagi sibuk persiapan pemilu', 'lagi sibuk persiapan pemilu', 'netral', '', '2023-12-10 23:41:44', 'pemilu2024'),
(27, '1733995411332020000', '@tempodotco @bawaslu_RI BANCI KALENG OLENG Takut Kehilangan Jabatan kok mau dipercaya jadi pengawas dan wasit pemilu Jujur Adil? Jauh...', 'BANCI KALENG OLENG Takut Kehilangan Jabatan kok mau dipercaya jadi pengawas dan wasit pemilu Jujur Adil? Jauh...', 'banci kaleng oleng takut kehilangan jabatan kok mau dipercaya jadi pengawas dan wasit pemilu Jujur Adil Jauh', 'negatif', '', '2023-12-10 23:41:36', 'pemilu2024'),
(28, '1733995323952150000', 'Singapura aman, kalo takut kalah jangan daftar pemilu..   Jangan takut pilih no 3 pasTIGAnjar ðŸ¤Ÿ https://t.co/0YPf1T3kVI', 'Singapura aman, kalo takut kalah jangan daftar pemilu..   Jangan takut pilih no 3 pasTIGAnjar ', 'singapura aman kalo takut kalah jangan daftar pemilu jangan takut pilih no 3 pastiganjar ', 'positif', '', '2023-12-10 23:41:15', 'pemilu2024'),
(29, '1733995316876320000', 'Antara Sainte Lague dan Konser Dangdut: Peta Persaingan Caleg Dalam Pemilu https://t.co/BKrMWk3AzG', 'Antara Sainte Lague dan Konser Dangdut: Peta Persaingan Caleg Dalam Pemilu ', 'antara sainte lague dan konser dangdut peta persaingan caleg dalam pemilu ', 'netral', '', '2023-12-10 23:41:15', 'pemilu2024'),
(30, '1733995078488850000', 'KPU Berikan Fasilitas Permudah Disabilitas pada Pemilu 2024  KPU telah mempersiapkan sarana dan prasarana bagi semua pemilih pada Pemilu tahun 2024 termasuk bagi Disabilitas.  Chelsea Roma Messi Girona #viralvideo Menhan Caicedo https://t.co/XROVwn9XW3', 'KPU Berikan Fasilitas Permudah Disabilitas pada Pemilu 2024  KPU telah mempersiapkan sarana dan prasarana bagi semua pemilih pada Pemilu tahun 2024 termasuk bagi Disabilitas.', 'kpu berikan fasilitas permudah disabilitas pada pemilu 2024  kpu telah mempersiapkan sarana dan prasarana bagi semua pemilih pada pemilu tahun 2024 termasuk bagi disabilitas', 'positif', '', '2023-12-10 23:40:17', 'pemilu2024'),
(31, '1733995022260030000', '@adearmando61 Mantap......siap2 tuk sujud syukur n stres lg kayak pemilu yg lalu', 'Mantap......siap2 tuk sujud syukur n stres lg kayak pemilu yg lalu', 'mantap siap2 tuk sujud syukur n stres lg kayak pemilu yg lalu', 'netral', '', '2023-12-10 23:40:04', 'pemilu2024'),
(32, '1733994855062540000', '@arfakevin16 @kim_didit @RukmanaYa21035 @Delphinibelle @PartaiSocmed terlepas dari masalah MK. siapa yang peduli? orang jokowi kerjaanya juga bagus. lagian pemilu juga yang milih rakyat bukan langsung ditunjuk oleh jokowi. rakyat tau kok mana yang bagus. kan ada hasilnya, daripada yang koar koar ngatain jokowi. malah dibenci sama rakyat wkwk', 'terlepas dari masalah MK. siapa yang peduli? orang jokowi kerjaanya juga bagus. lagian pemilu juga yang milih rakyat bukan langsung ditunjuk oleh jokowi. rakyat tau kok mana yang bagus. kan ada hasilnya, daripada yang koar koar ngatain jokowi. malah dibenci sama rakyat wkwk', 'terlepas dari masalah mk siapa yang peduli orang jokowi kerjaanya juga bagus lagian pemilu juga yang milih rakyat bukan langsung ditunjuk oleh jokowi rakyat tau kok mana yang bagus kan ada hasilnya daripada yang koar koar ngatain jokowi malah dibenci sama rakyat wkwk', 'netral', '', '2023-12-10 23:39:24', 'pemilu2024'),
(33, '1733994803170510000', '@tempodotco Wow hebat y bisa lolos @bawaslu_RI pakai orang dalem nich kya ny ðŸ˜ðŸ˜† jgn2 hasil pemilu nnti d curangi â“klw gtu urusan mu lngsung dgn allah yahâ˜ï¸', 'Wow hebat y bisa lolos pakai orang dalem nich kya ny  jgn2 hasil pemilu nnti d curangi klw gtu urusan mu lngsung dgn allah yah', 'wow hebat y bisa lolos pakai orang dalem nich kya ny  jgn2 hasil pemilu nnti d curangi klw gtu urusan mu lngsung dgn allah yah', 'negatif', '', '2023-12-10 23:39:11', 'pemilu2024'),
(34, '1733994773881750000', '@hermantoregar Mas Hermanto, tunggu hadiah setelah Pemilu (kalau jadi) selesai ya ! Ha3333x', 'Mas Hermanto, tunggu hadiah setelah Pemilu (kalau jadi) selesai ya ! Ha3333x', 'mas hermanto tunggu hadiah setelah pemilu kalau jadi selesai ya Ha3333x', 'netral', '', '2023-12-10 23:41:14', 'pemilu2024'),
(35, '1733994710778420000', '@icikiwir_08 @MIlyasa652 @yennywahid GUSDUR + AMIN  ga kau sebut serobot pemenang pemilu ? Eh giliran diturunin AMIN lu hilang kudeta ...KOCAK LU TONG', 'GUSDUR + AMIN  ga kau sebut serobot pemenang pemilu ? Eh giliran diturunin AMIN lu hilang kudeta ...KOCAK LU TONG', 'gusudr amin  ga kau sebut serobot pemenang pemilu eh giliran diturunin amin lu hilang kudeta kocak lu tong', 'negatif', '', '2023-12-10 23:38:49', 'pemilu2024'),
(36, '1733994396566360000', 'Babinsa desa Jegong Sertu Sutrisno melaksanakan kegiatan sosialisasi bersama warga masyarakat dukuh Kemadoh desa Jegong perihal cipta kondisi Pemilu tahun depan gunaÂ  mengetahui perkembangan yang setiap saat bisa terjadi. https://t.co/vx26wv6Fns', 'Babinsa desa Jegong Sertu Sutrisno melaksanakan kegiatan sosialisasi bersama warga masyarakat dukuh Kemadoh desa Jegong perihal cipta kondisi Pemilu tahun depan gunaÂ  mengetahui perkembangan yang setiap saat bisa terjadi. ', 'babinsa desa jegong sertu sutrisno melaksanakan kegiatan sosialisasi bersama warga masyarakat dukuh Kemadoh desa jegong perihal cipta kondisi Pemilu tahun depan guna  mengetahui perkembangan yang setiap saat bisa terjadi ', 'positif', '', '2023-12-10 23:37:34', 'pemilu2024'),
(37, '1733994359622930000', 'Babinsa desa Jegong Sertu Sutrisno melaksanakan kegiatan sosialisasi bersama warga masyarakat dukuh Kemadoh desa Jegong perihal cipta kondisi Pemilu tahun depan gunaÂ  mengetahui perkembangan yang setiap saat bisa terjadi. https://t.co/IdTir3eCqn', 'Babinsa desa Jegong Sertu Sutrisno melaksanakan kegiatan sosialisasi bersama warga masyarakat dukuh Kemadoh desa Jegong perihal cipta kondisi Pemilu tahun depan gunaÂ  mengetahui perkembangan yang setiap saat bisa terjadi. ', 'babinsa desa jegong sertu sutrisno melaksanakan kegiatan sosialisasi bersama warga masyarakat dukuh Kemadoh desa jegong perihal cipta kondisi Pemilu tahun depan guna  mengetahui perkembangan yang setiap saat bisa terjadi ', 'positif', '', '2023-12-10 23:37:26', 'pemilu2024'),
(38, '1733994316392210000', 'kekerasan anak yang terjadi pada pemilu sebelumnya. Tetaplah menjaga etika dan memprioritaskan kepentingan anak-anak.', 'kekerasan anak yang terjadi pada pemilu sebelumnya. Tetaplah menjaga etika dan memprioritaskan kepentingan anak-anak.', 'kekerasan anak yang terjadi pada pemilu sebelumnya tetaplah menjaga etika dan memprioritaskan kepentingan anak-anak', 'netral', '', '2023-12-10 23:37:15', 'pemilu2024'),
(39, '1733993992344470000', 'Hadiri Deklarasi Pemilu Damai 2024, Ini Kata Dandim 1806/Teluk Bintuni  Selengkapnya : https://t.co/lXALGlQlUc  #TNI #TNIADMemhbangunBersamaRakyat #Kodam18KasuariPatriotPelindungRakyat #TNIPeduli #TNIADMengabdiDanMembangunBersamaRakyat #tnisinergiuntuknegeri https://t.co/BQqeuqY2mi', 'Hadiri Deklarasi Pemilu Damai 2024, Ini Kata Dandim 1806/Teluk Bintuni  Selengkapnya ', 'hadiri deklarasi pemilu damai 2024 Ini kata dandim 1806 teluk bintuni  selengkapnya ', 'positif', '', '2023-12-10 23:35:58', 'pemilu2024'),
(40, '1733993825163780000', '@bangZhack86 Jika terbukti dari awal terjadi KECURANGAN seperti ini, KELAR pemilu KELARIN juga aja orang yg bertanggung jawab terhadap hal ini.ðŸ™ðŸ™ðŸ™âœŒï¸', 'Jika terbukti dari awal terjadi KECURANGAN seperti ini, KELAR pemilu KELARIN juga aja orang yg bertanggung jawab terhadap hal ini.', 'jika terbukti dari awal terjadi kecurangan seperti ini kelar pemilu kelarin juga aja orang yg bertanggung jawab terhadap hal ini', 'negatif', '', '2023-12-10 23:35:18', 'pemilu2024');

--
-- Indexes for dumped tables
--

--
-- Indeks untuk tabel `tweets`
--
ALTER TABLE `tweets`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT untuk tabel yang dibuang
--

--
-- AUTO_INCREMENT untuk tabel `tweets`
--
ALTER TABLE `tweets`
  MODIFY `id` int(12) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=41;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
